# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19dfb4d9c9c61bc9224bbd549e583a967bc9cee9ec6b0baad2cbd0f8003116bbc26bbc00dd7845a955e013391576c5b5bb5272f29280f3fdfd07cc3cbc212a32

test:
  secret_key_base: 4cdffb0ab1d611ebf7784a7182faf76d6e2f8ea5734e00f71f388466637540d82282160df6697f24cece4eeec7d31e9d58837049fc44151b3479bb0348e11c02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
